"""empty message

Revision ID: 3cbadc6cb529
Revises: 7a960e02b23f
Create Date: 2026-02-28 20:26:59.100130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbadc6cb529'
down_revision = '7a960e02b23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.Integer(), nullable=False))
        batch_op.drop_column('genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.INTEGER(), nullable=False))
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###
