"""empty message

Revision ID: 72646d640e02
Revises: 3cbadc6cb529
Create Date: 2026-03-02 18:55:35.594270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72646d640e02'
down_revision = '3cbadc6cb529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ratings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['Movie.movieId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'movieId', 'rating_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ratings')
    # ### end Alembic commands ###
