"""empty message

Revision ID: 7a960e02b23f
Revises: a4da699b3c9a
Create Date: 2026-02-28 20:24:34.241082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a960e02b23f'
down_revision = 'a4da699b3c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie',
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('genres', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('movieId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Movie')
    # ### end Alembic commands ###
