"""empty message

Revision ID: a9330d6ee393
Revises: 72646d640e02
Create Date: 2026-03-05 00:15:44.207976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9330d6ee393'
down_revision = '72646d640e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('nome_genres', sa.String(), nullable=False),
    sa.Column('genres_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('genres_id')
    )
    op.create_table('MovieGenre',
    sa.Column('genres_id', sa.Integer(), nullable=False),
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genres_id'], ['Genre.genres_id'], ),
    sa.ForeignKeyConstraint(['movieId'], ['Movie.movieId'], ),
    sa.PrimaryKeyConstraint('genres_id', 'movieId')
    )
    op.create_table('Rating',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movieId', sa.Integer(), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['Movie.movieId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.drop_table('Ratings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ratings',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('movieId', sa.INTEGER(), nullable=False),
    sa.Column('rating_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['Movie.movieId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'movieId', 'rating_id')
    )
    op.drop_table('Rating')
    op.drop_table('MovieGenre')
    op.drop_table('Genre')
    # ### end Alembic commands ###
